#!/bin/bash


# What this script does: 
#1. rename bashrc-it --> .bashrc-it
#2. make a backup of ~/.bashrc
#3. copy .bashrc-it & link with ~/.bashrc
#4. source ~/.bashrc

mv bashrc-it .bashrc-it
bshit="/home/${USER}/.bashrc-it" #_*yes. b-shit!*_

echo "backing up ~/.bashrc"
cp /home/${USER}/.bashrc .bashrc_bak 
cp .bashrc-it /home/${USER}/ && echo "source ${bshit}" >> /home/${USER}/.bashrc`
source /home/${USER}/.bashrc

echo "done!"
